---
title: "Assisted Migration Model"
author: "Ben Wasserman"
date: "`r Sys.Date()`"
output: html_document
---

#Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("print.matrix" = FALSE)
library(tidyverse)
library(spatstat.geom)
library(viridis)
library(rlang)
library(ggpubr)
library(foreach)
library(doParallel)
library(gganimate)
library(magick)
library(colorspace)
library(beepr)
```

#Define Functions
functions for different stages of the model: death, mate choice, reproduction, dispersal, environmental change
```{r functions}


#Identify Phenotypes
#using rowSums may speed it up over apply but I'll come back to this point
#apermPOPS213 <- aperm(POPS, perm = c(2,1,3)) 
#POPS[,7,] <- rowSums(aperm(POPS[,10:29,], na.rm = TRUE)
phenotypes <- function(z){
  z[,7,] <-apply(z[,10:29,], MARGIN = c(1,3), sum)
  z[,8,] <- apply(z[,30:49,], MARGIN = c(1,3), sum)  
  return(z)
  }

#Mortality
death <- function(w){
  #Phenotypic mismatch
  #Site Means
  LANDarray <- simplify2array(apply(LAND, MARGIN = 1, FUN = function(x) matrix(data = x, ncol = 2, nrow = K, byrow = TRUE), simplify = FALSE))
  
  #Compute mortality probability
  mortprob <- 1-(exp(((-1)*(w[,7,]-LANDarray[,1,])^2)/Omega2grad)*exp(((-1)*(w[,8,]-LANDarray[,2,])^2)/Omega2env)*S0)
   #Compute mortality
  w[,9,] <- rbinom(n=K*Si, size=1, prob=mortprob)

  deathfun <- function(y) {
    y[which(y[,9]==1),]<-NA
    y<-y[order(y[,1]),]
    return(y)
  }
  w <- simplify2array(apply(w, MARGIN = 3, FUN = deathfun, simplify = FALSE))
  return(w)
}



#Mate Choice
#Mate choice is going to be a function we apply to a single population matrix, and then we are going to apply it across the third dimension of the array
matechoice <- function(v){
  
  #Reset several columns from last time
  v[,4:6] <- 0
  mfcount <- c(sum(v[,1]==0, na.rm = TRUE), sum(v[,1]==1, na.rm = TRUE))
  mincount <- min(mfcount, na.rm = TRUE)
  femalemin <- as.numeric(mfcount[1]<=mfcount[2])
  
  if(femalemin == 1) {
    matedfemaleindex <- which(v[,1]==0)
  }
  if(femalemin == 0) {
    matedfemaleindex <- sample(which(v[,1]==0), size = mincount, replace = FALSE)
  }
  maleindex <- which(v[,1]==1)
  v[matedfemaleindex,4]<-1
  v[matedfemaleindex,5] <- sample(maleindex, size = mincount, replace = FALSE)
  
  #Generate the offspring number per female
  v[which((v[,4]==1)&(v[,1]==0)), 6] <- rpois(sum(v[,4], na.rm = TRUE), lambda = MuOff)
  
  return(v)
}



#reproduction

#function used inside the reproducedisperse 
#Takes a vector of length two, and gives you a vector  of integers from the first integer to the second
#But doesn't allow it to be more than carrying capacity, since this is going to be used to index available spots for propagulues to land
#Also, when nobody is there and nobody lands there, then the result is c(1,0), which we should change to NA
funct <- function(r) { 
        if(r[1]>K) {
          return(NA)
        }
        else if (r[1]>r[2]) {
          return(NA)
        }
        else {
          
          return(r[1]:r[2])
          }
      }

#Includes reproduction, mutation, dispersal
#In this case, x has to be the full population array
reproducedisperse <- function(u) {
  
   #if no offspring, we can close out of this function, just return the same population array
  if(sum(u[,6,],na.rm = TRUE)==0) return(u)
  
  #Parents: female id, population, father, offspring #
  parents<- matrix(cbind(which(u[,6,]!=0, arr.ind = TRUE), u[,5,][which(u[,6,]!=0)], u[,6,][which(u[,6,]!=0)])[,c(2,1,3,4)],ncol = 4)
  #parents <- matrix(parents[which(parents[,4]>0),], ncol = 4)
  
  #identify offspring characteristics and parents
  #cols: source pop, target pop, then the same cols as u...sex, momID, dadID, ...
   offspring <- matrix(data = NA_real_, nrow = sum(u[,6,], na.rm = TRUE), ncol = 11+2*L)
  offspring[,c(1,4,5)] <- matrix(parents[,1:3],ncol = 3)[rep(seq_along(parents[,4]), parents[,4]),]
  #This randomizes the order of offspring
  offspring <- matrix(offspring[sample(nrow(offspring)),], ncol = 11+2*L)
  #identify target population (trying to identify movement first, so that I can take fewer samples of 1/-1, since it won't matter for the 90% that don't move)
  #identify differential
  offspring[,2] <- rgeom(n = nrow(offspring), prob = MuMovement)
  #how many move
  nmigrants <- length(which(offspring[,2]!=0))
  #if they move, figure out if it's up or down
  offspring[which(offspring[,2]!=0),2] <- offspring[which(offspring[,2]!=0),2]*sample(c(1,-1), size = nmigrants, replace = TRUE) + offspring[which(offspring[,2]!=0),1]
  #if they didn't move, set same as parent
  offspring[which(offspring[,2]==0),2] <- offspring[which(offspring[,2]==0),1]
  #Keep them within the boundaries
  offspring[which(offspring[,2]<1),2] <- 1
  offspring[which(offspring[,2]>Si),2] <- Si
  
  #number of offspring landing per site
  noffspring <- tabulate(offspring[,2], nbins = Si)
  
  #number of openings in each site
  openings <- which(is.na(u[,1,]), arr.ind = TRUE)
  nopenings <- tabulate(openings[,2], nbins = Si)
  
  #nopportunities = minimum of #openings/#offspring attempting to land there
  nopportunities <- pmin(nopenings, noffspring)
  
  #if nopportunities = 0 then all spots are full, return the same population array
  if(sum(nopportunities)==0) return(u)

  #how do we sample offspring so that we have only nopportunities in each deme
  #The offspring have previously been randomly sorted. Now we sort them by target deme
  offspring <- matrix(offspring[order(offspring[,2]),], ncol = 11+2*L)
  
  #set up retained matrix
  offspringretained <- matrix(NA, nrow = sum(nopportunities, na.rm = TRUE), ncol = 11+2*L)
    
    #This function retains only the number of offspring that there are room for
    groupsample <- function(s){
      return(matrix(offspring[which(offspring[,2]==s),],ncol=ncol(offspring))[sample(nrow(matrix(offspring[which(offspring[,2]==s),],ncol = ncol(offspring))),size = nopportunities[s], replace = FALSE),])
    }
    offspringretained <- do.call(rbind, simplify2array(sapply(as.list(1:Si),FUN = groupsample, simplify=TRUE)))
    
    
    #Now I will fill in the genotypes of the sampled individuals
    #set sex
    offspringretained[,3]<- rbinom(n = sum(nopportunities, na.rm = TRUE), size = 1, prob = 0.5)
    #set genotypes
    

      
      
      moms <- matrix(data = NA_real_, nrow = nrow(offspringretained), ncol = 2*L)
      dads <- matrix(data = NA_real_, nrow = nrow(offspringretained), ncol = 2*L)
      moms <- matrix(u[cbind(rep(offspringretained[,4], each = 2*L), 10:49, rep(offspringretained[,1], each = 2*L))], nrow = nrow(offspringretained), ncol = 2*L, byrow = TRUE)
      dads <- matrix(u[cbind(rep(offspringretained[,5], each = 2*L), 10:49, rep(offspringretained[,1], each = 2*L))], nrow = nrow(offspringretained), ncol = 2*L, byrow = TRUE)               
      
      #now fill in the offspring retained genotypes by sampling from the correct parent options
      #Mom's grad values coming from her mom or dad
      #Note: This will break down if we change L
      offspringretained[,12] <- moms[cbind(1:nrow(offspringretained), sample(c(01,11), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,13] <- moms[cbind(1:nrow(offspringretained), sample(c(02,12), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,14] <- moms[cbind(1:nrow(offspringretained), sample(c(03,13), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,15] <- moms[cbind(1:nrow(offspringretained), sample(c(04,14), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,16] <- moms[cbind(1:nrow(offspringretained), sample(c(05,15), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,17] <- moms[cbind(1:nrow(offspringretained), sample(c(06,16), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,18] <- moms[cbind(1:nrow(offspringretained), sample(c(07,17), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,19] <- moms[cbind(1:nrow(offspringretained), sample(c(08,18), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,20] <- moms[cbind(1:nrow(offspringretained), sample(c(09,19), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,21] <- moms[cbind(1:nrow(offspringretained), sample(c(10,20), size = nrow(offspringretained), replace = TRUE))]
      #Dad's grad values coming from his mom or dad
      offspringretained[,22] <- dads[cbind(1:nrow(offspringretained), sample(c(01,11), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,23] <- dads[cbind(1:nrow(offspringretained), sample(c(02,12), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,24] <- dads[cbind(1:nrow(offspringretained), sample(c(03,13), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,25] <- dads[cbind(1:nrow(offspringretained), sample(c(04,14), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,26] <- dads[cbind(1:nrow(offspringretained), sample(c(05,15), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,27] <- dads[cbind(1:nrow(offspringretained), sample(c(06,16), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,28] <- dads[cbind(1:nrow(offspringretained), sample(c(07,17), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,29] <- dads[cbind(1:nrow(offspringretained), sample(c(08,18), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,30] <- dads[cbind(1:nrow(offspringretained), sample(c(09,19), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,31] <- dads[cbind(1:nrow(offspringretained), sample(c(10,20), size = nrow(offspringretained), replace = TRUE))]
      #Mom's  Env value coming from her mom or dad
      offspringretained[,32] <- moms[cbind(1:nrow(offspringretained), sample(c(21,31), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,33] <- moms[cbind(1:nrow(offspringretained), sample(c(22,32), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,34] <- moms[cbind(1:nrow(offspringretained), sample(c(23,33), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,35] <- moms[cbind(1:nrow(offspringretained), sample(c(24,34), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,36] <- moms[cbind(1:nrow(offspringretained), sample(c(25,35), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,37] <- moms[cbind(1:nrow(offspringretained), sample(c(26,36), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,38] <- moms[cbind(1:nrow(offspringretained), sample(c(27,37), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,39] <- moms[cbind(1:nrow(offspringretained), sample(c(28,38), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,40] <- moms[cbind(1:nrow(offspringretained), sample(c(29,39), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,41] <- moms[cbind(1:nrow(offspringretained), sample(c(30,40), size = nrow(offspringretained), replace = TRUE))]
      #Dad's Env value coming from his mom or dad
      offspringretained[,42] <- dads[cbind(1:nrow(offspringretained), sample(c(21,31), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,43] <- dads[cbind(1:nrow(offspringretained), sample(c(22,32), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,44] <- dads[cbind(1:nrow(offspringretained), sample(c(23,33), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,45] <- dads[cbind(1:nrow(offspringretained), sample(c(24,34), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,46] <- dads[cbind(1:nrow(offspringretained), sample(c(25,35), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,47] <- dads[cbind(1:nrow(offspringretained), sample(c(26,36), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,48] <- dads[cbind(1:nrow(offspringretained), sample(c(27,37), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,49] <- dads[cbind(1:nrow(offspringretained), sample(c(28,38), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,50] <- dads[cbind(1:nrow(offspringretained), sample(c(29,39), size = nrow(offspringretained), replace = TRUE))]
      offspringretained[,51] <- dads[cbind(1:nrow(offspringretained), sample(c(30,40), size = nrow(offspringretained), replace = TRUE))]
 
      #Identify and add mutations
      mutations <- matrix(data = rbinom(n = 2*L*dim(offspringretained)[1], size = 1, prob = 0.001), ncol = 2*L)
      mutations[which(mutations==1)] <-rnorm(n = sum(mutations), mean = 0, sd = 0.0005)
      offspringretained[,12:(11+2*L)]<- offspringretained[,12:(11+2*L)]+mutations
      
      
      #This is the basis for how we'll call the empty spaces to put the offspring in 
      
      #this should be all the empty spots we need, and we will fill it with the values from offspringretained
     
      
      #calculate population size
      popsize <- colSums(!is.na(u[,1,]))
      
      

      
      #this should be all the empty spots we need, and we will fill it with the values from offspringretained
      rowsneeded <- unlist(apply(cbind(popsize+1, popsize+nopportunities), MARGIN = 1, FUN = funct, simplify = TRUE))
      rowsneeded <- rowsneeded[which(!is.na(rowsneeded))]
      u[cbind(rep(rowsneeded, each = dim(u)[2]), 1:dim(u)[2], rep(1:Si, times = nopportunities*dim(u)[2]))]<-as.vector(t(offspringretained[,3:(11+2*L)]))
      
return(u)
}

#The genetic rescue is implemented using two functions
#donorrecipients identifies and saves a list of donor-recipient populations pairs
#rescue moves individuals from donor to recipient populations

#Rescue a function that moves some individuals around
#inputs: p is the POPS population array
#strategy is the type of genetic rescue strategy to use, below are the 5 options
#None: no rescue
#Demographic:  rescue from the geographically closest single population
#Grad: rescue based on the closest population to the ending value of Grad
#GradEnv: rescue based on the closest population to the ending values of Grad and Env (bivariate distance)
#Multiple: rescue based on a mix of 5 local populations
#The last parameter is donrecplist: a 2d matrix with 2 columns. The first column is the IDs of donors, the second column is the IDs of recipients. The matrix will have 1 row per recipient population, unless strategy = "Multiple" then it will have (RescueSourceNumber x the number of recipient populations) rows.


donorrecipients <- function(q, strategy){
  if(strategy == "None") return(matrix(NA_integer_, ncol = 2))
  #Now identify populations in need
  popsizes <- colSums(!is.na(POPS[,1,]))
  recipients <- sort(popsizes, index.return = TRUE)$ix[1:floor(Si*RescueSites)]
  eligibledonors <- (1:Si)[which(!(1:Si %in% recipients))]
  #setup donor recipient matrix
  drmat <- matrix(NA_integer_, ncol = 2, nrow = length(recipients)) #this assumes 1 row per recipient, we'll resave the empty matrix if strategy = "multiple"
  drmat[,2] <- recipients
    if(strategy == "Demographic") {
      drmat[,1] <- min(abs(drmat[,2]-eligibledonors)) 

  }
    
}

rescue <- function(p, strategy, donrecplist){
  if(strategy == "None") return(p)
  return(NULL)
}

#calculate population variance
popvar <- function(o){
  samplesize <- sum(!is.na(o))
  return(var(o, na.rm = TRUE)*(samplesize-1)/samplesize)
}

```

#Individual Simulation
(For Testing)

```{r individualsimulation}

###Set Constants

#Landscape Parameters
Si <- 50 #Number of sites
K <- 500 #Carrying capacity in each site
L <- 20 #Total number of Locii

#Population growth/adaptation parameters
phenvar <- 0.3 #Starting variance for values of each allele
Omega2grad <- 5 #selection strength for gradient
Omega2env <- 5 #selection strength for environment
S0 <- 0.75 #Baseline survival rate, there will always be some mortality, even for the perfectly adapted
MuOff <- 3 #Mean offspring per female per reproductive event
MuMovement <- 0.9 #Probability for the geometric distribution of staying still

#Simulation Length
timeperiod<- 600 

#Gradient Change parameters
#Note if deltaGradStart > timperiod, then there will be no gradient change
deltaGradStart <- 501 #Starting time point
deltaGradRate <- 0.05 #Change per time step
deltaGradLength <- 100 #Number of time steps

#Rescue parameters
#Note if RescueStart > timeperiod, then there will be no rescue
RescueStart <- 550 #Starting time point
RescueSites <- 0.1 #Proportion of sites to rescue (lowest RescueSites will be targeted for supplemental gene flow)
RescueSize <- 50 #Number of individual to send to each rescue site each year
RescueLength <- 3 #Number of time steps to repeat rescue over


#Mode is the type of genetic rescue strategy to use, below are the 5 options
#None: no rescue
#Demographic:  rescue from the geographically closest single population
#Grad: rescue based on the closest population to the ending value of Grad
#GradEnv: rescue based on the closest population to the ending values of Grad and Env (bivariate distance)
#Multiple: rescue based on a mix of 5 local populations, not based on Grad or Env
RescueMode <- "None" 
RescueSourceNumber <- 5 #Number of sources to pull from if mode = "Multiple"

#Is the environment variable or fixed?
EnvType <- "Variable"


###Setup landscape
  if (EnvType == "Variable") {
    LAND = data.frame(Grad = 1:Si, Env = sample(1:Si, replace = TRUE))
  } else if (EnvType == "Fixed") {
    LAND = data.frame(Grad = 1:Si, Env = as.integer(round(Si/2)))
  }

###Initialize Population Array

#50 sheets for 50 sites
#First 9 columns: Sex, MomID, DadID, Mate, MateID, Offspring#, GradPhenotype, EnvPhenotype, Died?
#MomID and DadID can just be the row number, not an ID column that we keep track of because it will just be used to determine genotype during the reproduction phase, then the info can be lost/reset
#Mate Binary indicator, will they mate this time step (1) or not (0) 
# MateID will be the row number of the mate, not an ID column
#Offspring # will be reset each time step
#GradMismatch and EnvMismatch shows how far the individual is from the mean
#As will Died?
#then there will be 40 columns per individual representing 2 alleles each for each of 20 locii - 10 related to Env, 10 related to Grad, the first 10 are the Grad from mom, next 10 are the Grad from dad, next 10 are the Env from mom, next 10 are the Env from dad

#Initialize Full population
POPS <- array(dim = c(K,9+2*L, Si))
#We can set Female = 0, Male = 1
POPS[,1,] <- sample(c(0,1), Si*K, replace = TRUE)
#Normal variation in genotype
POPS[,10:49,] <- rnorm(2*L*K*Si, 0, phenvar)
#Add Grad Mean to first 20 
POPS[,10:29,] <- POPS[,10:29,] + array(data = sort(rep(LAND$Grad/20, K*L)), dim = c(K, L, Si)) 
#Add Env Means to second 20
POPS[,30:49,] <- POPS[,30:49,] + array(data = as.vector(simplify2array(lapply(LAND$Env/20, rep, times = K*L), higher = TRUE)), dim = c(K, L, Si))

#Identify Phenotypes
#using rowSums may speed it up over apply but I'll come. ack to this point
#apermPOPS213 <- aperm(POPS, perm = c(2,1,3)) 
#POPS[,7,] <- rowSums(aperm(POPS[,10:29,], na.rm = TRUE)

  POPS[,7,] <-apply(POPS[,10:29,], MARGIN = c(1,3), sum)
  POPS[,8,] <- apply(POPS[,30:49,], MARGIN = c(1,3), sum)  
  

###Set contents for data collection

landgradovertime <- matrix(NA, nrow = timeperiod, ncol = Si)  
landenvovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
popovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
Gradovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
Envovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
FemaleRatioovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
Gradvarovertime <- matrix(NA, nrow = timeperiod, ncol = Si)
Envvarovertime <- matrix(NA, nrow = timeperiod, ncol = Si)


##Simulation
start_time <- Sys.time()
for(t in 1:timeperiod){
  #No environmental change except in this last else if statement
  if(t< deltaGradStart){
  } else if (t >= (deltaGradStart + deltaGradLength)){
  } else {LAND$Grad <- LAND$Grad + deltaGradRate}
  POPS <- death(POPS)
  POPS <- simplify2array(apply(POPS, MARGIN = 3, FUN = matechoice, simplify = FALSE))
  POPS <- reproducedisperse(POPS)
  POPS <- phenotypes(POPS)
  if(t == RescueStart) donorrecipientslist <- donorrecipients(POPS, strategy = RescueMode)
  # Need to identify when rescues will happen
  #if(t POPS <- rescue(POPS, strategy = "Grad")
  landgradovertime[t,] <- LAND$Grad
  landenvovertime[t,] <- LAND$Env
  popovertime[t,] <- colSums(!is.na(POPS[,1,]))
  Gradovertime[t,] <- colSums(POPS[,7,],na.rm = TRUE)/colSums(!is.na(POPS[,7,]), na.rm = TRUE)-LAND$Grad
  Envovertime[t,] <- colSums(POPS[,8,],na.rm = TRUE)/colSums(!is.na(POPS[,8,]), na.rm = TRUE)-LAND$Env
  FemaleRatioovertime[t,] <- colSums(POPS[,1,]==1,na.rm = TRUE)/popovertime[t,]
  #I'm still developing this Gradvarovertime
  Gradvarovertime[t,] <- apply(POPS[,7,], MARGIN = 2, FUN = popvar)
  Envvarovertime[t,] <- apply(POPS[,8,], MARGIN = 2, FUN = popvar)
  print(paste("Step",t,Sys.time()))
  #Cancel the remainder of the simulation if the entire metapopulation dies out
  if (sum(POPS[,1,], na.rm = TRUE)==0) break

}
end_time <- Sys.time()
end_time - start_time



###PLot all populations over time
matplot(popovertime)
matplot(Gradovertime)
matplot(Envovertime)
matplot(Gradvarovertime)
matplot(Envvarovertime)

#Check Population Sizes
colSums(!is.na(POPS[,1,]))

#How many of each sex
colSums(POPS[,1,],na.rm = TRUE)
colSums(POPS[,1,]==0, na.rm = TRUE)
colSums(!is.na(POPS[,1,]))

#Ending conditions
plot(Gradovertime[timeperiod,]+LAND$Grad ~ LAND$Grad, ylab = "Phenotype - Grad", xlab = "Grad")
points(LAND$Grad~LAND$Grad, col = "red")

plot(Envovertime[timeperiod,]+LAND$Env ~ LAND$Grad, ylab = "Phenotype - Env", xlab = "Grad")
points(LAND$Env~LAND$Grad, col = "red")



distancefromneighbor <- rowSums(cbind(abs(LAND$Env-lag(LAND$Env)),abs(LAND$Env-lead(LAND$Env))),na.rm=TRUE)/c(1,rep(2,Si-2),1)
plot(popovertime[timeperiod,]~distancefromneighbor)

plot(Gradovertime[timeperiod,])

par(mfrow = c(3,1))
matplot(popovertime)
matplot(Gradovertime)
matplot(Envovertime)
par(mfrow = c(1,1))


#Setting up to animate a full single simulation

simdata <- data.frame(Site = NA_integer_, Time = NA_integer_, Variable = NA_character_, Value = NA_real_)

landgradovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Land.Grad", Value = as.vector(landgradovertime))
landenvovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Land.Env", Value = as.vector(landenvovertime))
popovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Pop.Size", Value = as.vector(popovertime))
gradovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Grad.Maladapt", Value = as.vector(Gradovertime))
envovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Env.Maladapt", Value = as.vector(Envovertime))
gradvarovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Grad.Var", Value = as.vector(Gradvarovertime))
envvarovertimedf <- data.frame(Site = rep(1:Si, each = timeperiod), Time = rep(1:timeperiod, times = Si), Variable = "Env.Var", Value = as.vector(Envvarovertime))
dataovertimedf <- rbind(popovertimedf, gradovertimedf, envovertimedf, gradvarovertimedf, envvarovertimedf)
dataovertimedf$Variable <- factor(dataovertimedf$Variable, levels = c("Pop.Size", "Grad.Maladapt", "Grad.Var", "Env.Maladapt", "Env.Var"))


landgradplot <- ggplot(data = landgradovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_viridis(limits = c(0,Si), option = "G") +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
landgradanim <- landgradplot + labs(title = "{closest_state}") + transition_states(Time)
landgradgif <- animate(landgradanim, nframes = timeperiod, width = 200)

landenvplot <- ggplot(data = landenvovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_viridis(limits = c(0,Si), option = "G") +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
landenvanim <- landenvplot + labs(title = "{closest_state}") + transition_states(Time)
landenvgif <- animate(landenvanim, nframes = timeperiod, width = 200)

popplot <- ggplot(data = popovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_viridis(limits = c(0,K), option = "D") +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
popanim <- popplot + labs(title = "{closest_state}") + transition_states(Time)
popgif <- animate(popanim, nframes = timeperiod, width = 200)

gradplot <- ggplot(data = gradovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_continuous_divergingx(palette = 'RdBu') +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
gradanim <- gradplot + labs(title = "{closest_state}") + transition_states(Time)
gradgif <- animate(gradanim, nframes = timeperiod, width = 200)

envplot <- ggplot(data = envovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_continuous_divergingx(palette = 'RdBu') +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
envanim <- envplot + labs(title = "{closest_state}") + transition_states(Time)
envgif <- animate(envanim, nframes = timeperiod, width = 200)

gradvarplot <- ggplot(data = gradvarovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_viridis(option = "B") +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
gradvaranim <- gradvarplot + labs(title = "{closest_state}") + transition_states(Time)
gradvargif <- animate(gradvaranim, nframes = timeperiod, width = 200)

envvarplot <- ggplot(data = envvarovertimedf, aes(x = Variable, y = Site)) + geom_raster(aes(fill = Value)) + scale_fill_viridis(option = "B") +  xlab(NULL) + theme_classic() + theme(legend.position = "top", axis.line.x = element_blank(), axis.ticks.x = element_blank())
envvaranim <- envvarplot + labs(title = "{closest_state}") + transition_states(Time)
envvargif <- animate(envvaranim, nframes = timeperiod, width = 200)



new_gif <- image_append(c(landgradgif[1], gradgif[1], gradvargif[1], landenvgif[1], envgif[1], envvargif[1], popgif[1]))
for(i in 2:timeperiod){
  combined <- image_append(c(landgradgif[i], gradgif[i], gradvargif[i], landenvgif[i], envgif[i], envvargif[i], popgif[i]))
  new_gif <- c(new_gif, combined)
}

new_gif


beep(sound = 6)
```



#Sensitivity Analysis 
Execute the simulation function over a range of values
```{r Sensitivity}
#Set parameters that will be used the same in all simulations
#Landscape Parameters
Si <- 50 #Number of sites
K <- 500 #Carrying capacity in each site
L <- 20 #Total number of Locii

#Population growth/adaptation parameters
phenvar <- 0.3 #Starting variance for values of each allele
S0 <- 0.75 #Baseline survival rate, there will always be some mortality, even for the perfectly adapted
MuOff <- 6 #Mean offspring per female per reproductive event

#Simulation Length
timeperiod<- 600 

#Gradient Change parameters
#Note if deltaGradStart > timperiod, then there will be no gradient change
deltaGradStart <- 501 #Starting time point
deltaGradRate <- 0.05 #Change per time step
deltaGradLength <- 100 #Number of time steps

#Rescue parameters
#Note if RescueStart > timeperiod, then there will be no rescue
RescueStart <- 550 #Starting time point
RescueSites <- 0.1 #Proportion of sites to rescue (lowest RescueSites will be targeted for supplemental gene flow)
RescueSize <- 50 #Number of individual to send to each rescue site each year
RescueLength <- 3 #Number of time steps to repeat rescue over


#Mode is the type of genetic rescue strategy to use, below are the 5 options
#None: no rescue
#Demographic:  rescue from the geographically closest single population
#Grad: rescue based on the closest population to the ending value of Grad
#GradEnv: rescue based on the closest population to the ending values of Grad and Env (bivariate distance)
#Multiple: rescue based on a mix of 5 local populations, not based on Grad or Env
RescueMode <- "None" 
RescueSourceNumber <- 5 #Number of sources to pull from if mode = "Multiple"


#Set values for parameters (migration, selection, environment type (fixed or variable))
MigSelvals <- data.frame(Mig = rep(c(0.9, 0.99, 0.999, 0.9999, 0.99999, 1),each = 20), Sel = rep(1:10,12), Envmode = c(rep("Fixed",10), rep("Variable",10)))


#Set up data collection
MigSel <-array(data = NA, dim = c(6,Si,dim(MigSelvals)[1]))
LANDrecord <- array(data = NA, dim = c(Si, 2, dim(MigSelvals)[1]))
giflist <- vector(mode = "list", length = dim(MigSelVals[1]))

#How long does the loop take?
start_time <- Sys.time()
#The outer for-loop loops over different sets of parameter values, as established in MigSelvals
for (i in 1:dim(MigSelvals)[1]) {
  #I'm just testing this, in the line above, I'm going to have to restore the upper value of i to dim(MigSelvals)[1]
  #Set temporary values of variables
  Omega2grad <- MigSelvals$Sel[i]
  Omega2env <- MigSelvals$Sel[i]
  MuMovement <- MigSelvals$Mig[i]
  EnvType <- MigSelvals$Envmode[i]
  
  #Setup landscape
  if (EnvType == "Variable") {
    LAND = data.frame(Grad = 1:Si, Env = sample(1:Si, replace = TRUE))
  } else if (EnvType == "Fixed") {
    LAND = data.frame(Grad = 1:Si, Env = as.integer(round(Si/2)))
  }

  #Initialize Full population
  POPsim <- array(dim = c(K,9+2*L, Si))
  #We can set Female = 0, Male = 1
  POPsim[,1,] <- sample(c(0,1), Si*K, replace = TRUE)
  #Normal variation in genotype
  POPsim[,10:49,] <- rnorm(2*L*K*Si, 0, phenvar)
  #Add Grad Mean to first 20 
  POPsim[,10:29,] <- POPsim[,10:29,] + array(data = sort(rep(LAND$Grad/20, K*L)), dim = c(K, L, Si)) 
  #Add Env Means to second 20
  POPsim[,30:49,] <- POPsim[,30:49,] + array(data = as.vector(simplify2array(lapply(LAND$Env/20, rep, times = K*L), higher = TRUE)), dim = c(K, L, Si))

  #Identify Phenotypes
  POPsim[,7,] <-apply(POPsim[,10:29,], MARGIN = c(1,3), sum)
  POPsim[,8,] <- apply(POPsim[,30:49,], MARGIN = c(1,3), sum)  

  #Simulate population and evolutionary dynamics with these parameters
  for(t in 1:timeperiod){
    #No environmental change except in this last else if statement
    if(t< deltaGradStart){
    } else if (t >= (deltaGradStart + deltaGradLength)){
    } else {LAND$Grad <- LAND$Grad + deltaGradRate}
    POPsim <- death(POPsim)
    POPsim <- simplify2array(apply(POPsim, MARGIN = 3, FUN = matechoice, simplify = FALSE))
    POPsim <- reproducedisperse(POPsim)
    POPsim <- phenotypes(POPsim)
    if(t == RescueStart) donorrecipientslist <- donorrecipients(POPsim, strategy = RescueMode)
    # Need to identify when rescues will happen
    #if(t POPS <- rescue(POPS, strategy = "Grad")
    #Cancel the remainder of the simulation if the entire metapopulation dies out
    if (sum(POPsim[,1,], na.rm = TRUE)==0) break
  }
  
  #Save Ending population information
  enddata <- matrix(NA, nrow = 6, ncol = Si)
  enddata[1,]<- colSums(!is.na(POPsim[,1,]))
  #Maladaptation
  enddata[2,] <- colSums(POPsim[,7,],na.rm = TRUE)/colSums(!is.na(POPsim[,7,]), na.rm = TRUE)-LAND$Grad
  enddata[3,] <- colSums(POPsim[,8,],na.rm = TRUE)/colSums(!is.na(POPsim[,8,]), na.rm = TRUE)-LAND$Env
  #Phenotypic variance
  #variance for gradient
  enddata[4,] <- apply(POPsim[,7,], MARGIN = 2, FUN = popvar)
  #variance for environment
  enddata[5,] <- apply(POPsim[,8,], MARGIN = 2, FUN = popvar)
  enddata[6,] <- t

  #Save information into big dataset before next step
  MigSel[,,i] <- enddata
  LANDrecord[,,i] <- as.matrix(LAND)
  
  #Update Counter
  print(paste("Step",i,"out of",dim(MigSelvals)[1],Sys.time()))
} 
end_time <- Sys.time()
end_time - start_time
save(MigSelvals, MigSel, LANDrecord, file = "Outputs/Sensitivity/NoRescue2023_11_29a.Rdata")

```

#Sensitivity Plots
```{r sensitivityplots}

#Summarize data

#Calculate means
means <- apply(MigSel, MARGIN = c(1,3), FUN = mean, na.rm = TRUE)
#Extant Populations Pre-Grad Change
extantPreGC <- means[6,]>=deltaGradStart
#Extant Populations Post-Grad Change
extantPostGC <- means[6,]==timeperiod
#Populations Over K*4/5
bigpops <- colSums(MigSel[1,,]>(K*4/5))
#Populations Over K*1/5
notsmallpops <- colSums(MigSel[1,,]>(K/5))
#Mean Population Size
popmeans <- means[1,]
#Median Population Size
popmeds <- apply(MigSel[1,,], MARGIN = 2, FUN = median)
#Standard Deviation of Population Size
popsds <- apply(MigSel[1,,], MARGIN = 2, FUN = sd)

#Grad

#Mean Population level Maladaptation (Grad Phenotype - Grad)
gradmeans <- means[2,]
#Standard Deviation of Population level Maladaptation to Grad
gradsds <- apply(MigSel[2,,], MARGIN = 2, FUN = sd, na.rm = TRUE)
#Mean Population level Maladaptation (Env Phenotype - Env)
envmeans <- means[3,]
#Standard Deviation of Population level Maladaptation to Env
envsds <- apply(MigSel[3,,], MARGIN = 2, FUN = sd, na.rm = TRUE)

#The mean of the within-population variance for phenotype (Grad)
gradvars <- means[4,]
#The standard deviation of the within-population variances for phenotype (Grad)
gradvarssds <- apply(MigSel[4,,], MARGIN = 2, FUN = sd, na.rm = TRUE)
#The mean of the within-population variance for phenotype (Env)
envvars <- means[5,]
#The standard deviation of the within-population variances for phenotype (Env)
envvarssds <- apply(MigSel[5,,], MARGIN = 2, FUN = sd, na.rm = TRUE)

plotdata <- data.frame(Mig = MigSelvals$Mig, Sel = MigSelvals$Sel, Envmode = MigSelvals$Envmode, extantPreGC, extantPostGC, bigpops, notsmallpops, popmeans, popmeds, popsds, gradmeans, gradsds, envmeans, envsds, gradvars, gradvarssds, envvars, envvarssds) %>% mutate(extantPreGC = as.numeric(extantPreGC), extantPostGC = as.numeric(extantPostGC))

plotdatalong <- plotdata %>% pivot_longer(cols = 4:18, names_to = "Response", values_to = "Value")

ggplot(data = plotdatalong, aes(x = Mig, y = Sel)) + facet_grid(rows = vars(Response), cols = vars(Envmode)) + geom_raster(aes(fill = Value)) + scale_fill_viridis() + theme_classic()

popplotdatalong <- plotdatalong %>% filter(Response %in% names(plotdata)[4:10]) %>% droplevels()
adaptplotdatalong <- plotdatalong %>% filter(Response %in% names(plotdata[11:18])) %>% droplevels()

ggplot(data = popplotdatalong, aes(x = Mig, y = Sel)) + facet_grid(rows = vars(Response), cols = vars(Envmode)) + geom_raster(aes(fill = Value)) + scale_fill_viridis() + theme_classic()

ggplot(data = adaptplotdatalong, aes(x = Mig, y = Sel)) + facet_grid(rows = vars(Response), cols = vars(Envmode)) + geom_raster(aes(fill = Value)) + scale_fill_viridis() + theme_classic()

#Test Plot
ggplot(data = filter(plotdata, Envmode == "Fixed"), aes(x = (1.000001-Mig), y = (11-Sel))) + geom_raster(aes(fill = popmeans)) + scale_fill_viridis() + scale_x_continuous(breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01"), trans = "log10") + xlab("Proportion of Migrants") + ylab("Selection Strength") + theme_classic()

plotlistfixed <-vector(mode = "list", length = 15)
plotlistvariable <-vector(mode = "list", length = 15)
for(i in names(plotdata)[4:18]){
  plotlistfixed[[i]] <- local({
        i <- i
        ggplot(data = filter(plotdata, Envmode == "Fixed"), aes(x = (1.000001-Mig), y = (11-Sel))) + geom_raster(aes(fill = .data[[i]])) + scale_fill_viridis() + scale_x_continuous(breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01"), trans = "log10") + xlab("Proportion Migrants") + ylab("Selection Strength") + theme_classic()
        })
  plotlistvariable[[(i)]] <- local({
        i <- i
        ggplot(data = filter(plotdata, Envmode == "Variable"), aes(x = (1.000001-Mig), y = (11-Sel))) + geom_raster(aes(fill = .data[[i]])) + scale_fill_viridis() + scale_x_continuous(breaks = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01"), trans = "log10") + xlab("Proportion Migrants") + ylab("Selection Strength") + theme_classic()
  })
  }


pdf(file = "Outputs/Sensitivity/NoRescue2023_11_29a_Plots_Fixed.pdf", height = 10, width = 7.5)
ggpubr::ggarrange(plotlist = plotlistfixed, ncol = 2, nrow = 6, byrow = FALSE)
dev.off()


pdf(file = "Outputs/Sensitivity/NoRescue2023_11_29a_Plots_Variable.pdf", height = 10, width = 7.5)
ggpubr::ggarrange(plotlist = plotlistvariable, ncol = 2, nrow = 6, byrow = FALSE)
dev.off()


```

