---
title: "Parallel Processing Plots"
author: "Ben Wasserman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(viridis)
library(ggpubr)
library(colorspace)
library(grid)
library(gdata)
library(str2str)
```

```{r loaddata}
load("Outputs/Parallel/Test_2024_03_20_Outputs.Rdata")
```

```{r organizedata}


#This gets us a 3d array with all of the outputs
datalist <- lapply(results_mclapply, FUN = "[[", 1)
dataarray <- ld2a(datalist)

landlist <- lapply(results_mclapply, FUN = "[[", 2)
landarray <- ld2a(landlist)


#This is the final landscape value for for each site
landgradmatfinal <- landarray[,1,]+matrix(Paramdf$deltaGradLength*Paramdf$deltaGradRate, byrow = TRUE, nrow = mean(Paramdf$Si), ncol = dim(Paramdf)[1])
landenvmatfinal <- landarray[,1,]+matrix(Paramdf$deltaGradLength*Paramdf$deltaGradRate, byrow = TRUE, nrow = mean(Paramdf$Si), ncol = dim(Paramdf)[1])

#Get the values at the endpoint
poplist <- lapply(datalist, FUN = filter, ((Variable == "Pop.Size") & (Time == 600))) 
gradlist <- lapply(datalist, FUN = filter, ((Variable == "Grad") & (Time == 600))) 
envlist <- lapply(datalist, FUN = filter, ((Variable == "Env") & (Time == 600)))
gradvarlist <- lapply(datalist, FUN = filter, ((Variable == "Grad.Var") & (Time == 600)))
envvarlist <- lapply(datalist, FUN = filter, ((Variable == "Env.Var") & (Time == 600)))

#Find differential from optimum
Gradmatfinal <- simplify2array(sapply(gradlist, "[", 4, simplify = "array"))
Paramdf$Maladapt.Grad <- Gradmatfinal - landgradmatfinal
Envmatfinal <- simplify2array(sapply(envlist, "[", 4, simplify = "array"))
Paramdf$Maladapt.Env <- Envmatfinal - landenvmatfinal

Paramdf$PopSizeFinal <- sapply(poplist, function(x) mean(x$Value))
Paramdf$GradVarFinal <- sapply(poplist, function(x) mean(x$Value))
Paramdf$EnvVarFinal <- sapply(poplist, function(x) mean(x$Value))

ggplot(data = Paramdf, aes(x = log10(Mig), y = Omega2grad)) + geom_tile(aes(fill = PopSizeFinal)) + scale_fill_viridis()

```


