---
title: "Plots_RescueData"
author: "Ben Wasserman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(viridis)
library(ggpubr)
library(colorspace)
library(grid)
library(gdata)
library(str2str)
library(parallel)
library(beepr)

```

```{r loaddata}

#load("RescueDataUpdated.Rdata")
#load("RescueDataMutationTest3.Rdata")
load("RescueData_Revision.Rdata")
#load("Rescuedata_omega20.Rdata")
```

```{r plotallpops}

#To add the omega2grad = 20 data but keep these tiles the same, I manually recoded to 12, but I need to turn that off for future uses
Paramsum$Sel[which(Paramsum$Sel==(0.05))]<-(1/12)
rescuecombplot$Sel[which(rescuecombplot$Sel==(0.05))]<-(1/12)
rescue_recipcombplot$Sel[which(rescue_recipcombplot$Sel==(0.05))]<-(1/12)

difflabs <- c("Nearest Neighbor", "Match 1EV", "Match 2EVs", "Match Phenotypes", "Multiple Nearest Neighbors", "Adjust for 1EV", "Adjust for 2EV")
names(difflabs) <- c("DemographicDiff", "GradDiff", "GradEnvDiff", "PhenDiff", "MultipleDiff", "GradAdjDiff", "GradEnvAdjDiff")

xsmalltxtsize <- 6
smalltxtsize <- 8
lgtxtsize <- 8

 keywidth <- 0.9
  keyheight <- 0.9

#Fixed Environment

fexplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Extant"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Populations\nExtant", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Extant")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize))


fpsplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Pop.Size"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Population\nSize", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Pop.Size")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fgmplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Grad.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Maladaptation", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Grad.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

femplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Env.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Maladaptation", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "Env.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fgvplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "GradVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Phenotypic\nVariance", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "GradVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fevplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "EnvVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Phenotypic\nVariance", limits = range(filter(rescuecombplot, ((EnvType == "Fixed")&(Variable == "EnvVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fixedplot <- ggarrange(fexplot, fpsplot, fgmplot, femplot, fgvplot, fevplot, ncol = 1)
fixedplot2 <- annotate_figure(fixedplot, left = textGrob("Selection Strength (1/omega^2)", rot = 90, vjust = 1, gp = gpar(cex=1)), bottom = textGrob("Proportion Migrants", vjust= -0.25, gp = gpar(cex = 1)), top = textGrob("All Populations Averaged, EV2 Invariant", gp = gpar(cex=1)))

#ggsave(fixedplot2, filename = "./Outputs/V3 Figures/diffplot_fixed_updated_2025_11_24.wmf", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2, filename = "./Outputs/V4 Figures/diffplot_fixed_mutationtest2_updated_2026_03_29.wmf", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2, filename = "./Outputs/V4 Figures/diffplot_fixed_mutationtest3_updated_2026_03_29.png", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2, filename = "./Outputs/V4 Figures/diffplot_fixed_2026_06_07.png", height = 10, width = 7.5, units = "in")

ggsave(fixedplot2, filename = "./Outputs/V4 Figures/diffplot_fixed_omega2_2026_06_25.png", height = 10, width = 7.5, units = "in")

  
#pdf(file = "./Outputs/V3 Figures/diffplot_fixed_updated_2025_11_24.pdf", height = 10, width = 7.5)
#fixedplot2
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_fixed_mutationtest3_updated_2026_03_29.pdf", height = 10, width = 7.5)
#fixedplot2
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_fixed_2026_06_07.pdf", height = 10, width = 7.5)
#fixedplot2
#dev.off()

pdf(file = "./Outputs/V4 Figures/diffplot_fixed_omega2_2026_06_25.pdf", height = 10, width = 7.5)
fixedplot2
dev.off()

#Variable Environment  

vexplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Extant"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Populations\nExtant", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Extant")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize))

vpsplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Pop.Size"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Population\nSize", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Pop.Size")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vgmplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Grad.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Maladaptation", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Grad.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vemplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Env.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Maladaptation", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "Env.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vgvplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "GradVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Phenotypic\nVariance", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "GradVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vevplot <- ggplot(data = filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "EnvVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Phenotypic\nVariance", limits = range(filter(rescuecombplot, ((EnvType == "Variable")&(Variable == "EnvVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

variableplot <- ggarrange(vexplot, vpsplot, vgmplot, vemplot, vgvplot, vevplot, ncol = 1)
variableplot2 <- annotate_figure(variableplot, left = textGrob("Selection Strength (1/omega^2)", rot = 90, vjust = 1, gp = gpar(cex=1)), bottom = textGrob("Proportion Migrants", vjust= -0.25, gp = gpar(cex = 1)), top = textGrob("All Populations Averaged, EV2 Spatially Variant", gp = gpar(cex=1))) + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))


#ggsave(variableplot2, filename = "./Outputs/V3 Figures/diffplot_variable_updated_2025_11_24.wmf", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2, filename = "./Outputs/V4 Figures/diffplot_variable_mutationtest2_updated_2026_03_29.wmf", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2, filename = "./Outputs/V3 Figures/diffplot_variable_updated_2025_11_24.png", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2, filename = "./Outputs/V4 Figures/diffplot_variable_mutationtest3_updated_2026_03_29.png", height = 10, width = 7.5, units = "in")
  
#ggsave(variableplot2, filename = "./Outputs/V4 Figures/diffplot_variable_2026_06_07.png", height = 10, width = 7.5, units = "in")

ggsave(variableplot2, filename = "./Outputs/V4 Figures/diffplot_variable_omega20_2026_06_25.png", height = 10, width = 7.5, units = "in")

#pdf(file = "./Outputs/V3 Figures/diffplot_variable_updated_2025_11_24.pdf", height = 10, width = 7.5)
#variableplot2
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_variable_mutationtest3_updated_2026_03_29.pdf", height = 10, width = 7.5)
#variableplot2
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_variable_2026_06_07.pdf", height = 10, width = 7.5)
#variableplot2
#dev.off()

pdf(file = "./Outputs/V4 Figures/diffplot_variable_omega20_2026_06_25.pdf", height = 10, width = 7.5)
variableplot2
dev.off()

```


```{r plotrecipientpops}

#Fixed Environment

fexplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Extant"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Populations\nExtant", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Extant")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize))

fpsplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Pop.Size"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Population\nSize", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Pop.Size")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fgmplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Grad.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Maladaptation", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Grad.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

femplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Env.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Maladaptation", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "Env.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fgvplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "GradVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Phenotypic\nVariance", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "GradVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fevplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "EnvVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Phenotypic\nVariance", limits = range(filter(rescue_recipcombplot, ((EnvType == "Fixed")&(Variable == "EnvVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

fixedplot_recip <- ggarrange(fexplot_recip, fpsplot_recip, fgmplot_recip, femplot_recip, fgvplot_recip, fevplot_recip, ncol = 1)
fixedplot2_recip <- annotate_figure(fixedplot_recip, left = textGrob("Selection Strength (1/omega^2)", rot = 90, vjust = 1, gp = gpar(cex=1)), bottom = textGrob("Proportion Migrants", vjust= -0.25, gp = gpar(cex = 1)), top = textGrob("Recipient Populations Only, EV2 Invariant", gp = gpar(cex=1)))

#ggsave(fixedplot2_recip, filename = "./Outputs/V3 Figures/diffplot_fixed_recipientsonly_updated_2025_11_24.wmf", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2_recip, filename = "./Outputs/V4 Figures/diffplot_fixed_mutationtest2_recipientsonly_updated_2026_03_29.wmf", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2_recip, filename = "./Outputs/V3 Figures/diffplot_fixed_recipientsonly_updated_2025_11_24.png", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2_recip, filename = "./Outputs/V4 Figures/diffplot_fixed_mutationtest3_recipientsonly_updated_2026_03_29.png", height = 10, width = 7.5, units = "in")

#ggsave(fixedplot2_recip, filename = "./Outputs/V4 Figures/diffplot_fixed_recipientsonly_2026_06_07.png", height = 10, width = 7.5, units = "in")

 ggsave(fixedplot2_recip, filename = "./Outputs/V4 Figures/diffplot_fixed_recipientsonly_omega20_2026_06_25.png", height = 10, width = 7.5, units = "in")
 
#pdf(file = "./Outputs/V3 Figures/diffplot_fixed_recipientsonly_updated_2025_11_24.pdf", height = 10, width = 7.5)
#fixedplot2_recip
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_fixed_mutationtest3_recipientsonly_updated_2026_03_29.pdf", height = 10, width = 7.5)
#fixedplot2_recip
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_fixed_recipientsonly_u2026_06_07.pdf", height = 10, width = 7.5)
#fixedplot2_recip
#dev.off()

pdf(file = "./Outputs/V4 Figures/diffplot_fixed_recipientsonly_omega20_2026_06_25.pdf", height = 10, width = 7.5)
fixedplot2_recip
dev.off()

#Variable Environment  

vexplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Extant"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Populations\nExtant", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Extant")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize))

vpsplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Pop.Size"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "Population\nSize", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Pop.Size")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vgmplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Grad.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Maladaptation", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Grad.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vemplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Env.Maladaptation"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Maladaptation", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "Env.Maladaptation")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vgvplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "GradVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV1 Phenotypic\nVariance", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "GradVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

vevplot_recip <- ggplot(data = filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "EnvVar"))), aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Value)) + geom_tile() + facet_grid(.~Diff, labeller = labeller(Diff = difflabs)) + scale_fill_gradient2(name = "EV2 Phenotypic\nVariance", limits = range(filter(rescue_recipcombplot, ((EnvType == "Variable")&(Variable == "EnvVar")))$Value), low = "red", mid = "white", high = "blue", midpoint = 0) + scale_x_continuous(name = NULL, breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize, color = 'white'), strip.background = element_rect(color = 'white'))

variableplot_recip <- ggarrange(vexplot_recip, vpsplot_recip, vgmplot_recip, vemplot_recip, vgvplot_recip, vevplot_recip, ncol = 1)
variableplot2_recip <- annotate_figure(variableplot_recip, left = textGrob("Selection Strength (1/omega^2)", rot = 90, vjust = 1, gp = gpar(cex=1)), bottom = textGrob("Proportion Migrants", vjust= -0.25, gp = gpar(cex = 1)), top = textGrob("Recipient Populations Only, EV2 Spatially Variant", gp = gpar(cex=1))) + theme(axis.text.y = element_text(size = xsmalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1), legend.title=element_text(size = lgtxtsize), legend.text = element_text(size = smalltxtsize), legend.key.width = unit(keywidth, "lines"), legend.key.height = unit(keyheight, "lines"), strip.text = element_text(size = xsmalltxtsize))


#ggsave(variableplot2_recip, filename = "./Outputs/V3 Figures/diffplot_variable_recipientsonlyupdated_2025_11_24.wmf", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2_recip, filename = "./Outputs/V4 Figures/diffplot_variable_mutationtest2_recipientsonlyupdated_2026_03_29.wmf", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2_recip, filename = "./Outputs/V3 Figures/diffplot_variable_recipientsonlyupdated_2025_11_24.png", height = 10, width = 7.5, units = "in")

#ggsave(variableplot2_recip, filename = "./Outputs/V4 Figures/diffplot_variable_mutationtest3_recipientsonlyupdated_2026_03_29.png", height = 10, width = 7.5, units = "in")
  
#ggsave(variableplot2_recip, filename = "./Outputs/V4 Figures/diffplot_variable_recipientsonly_2026_06_07.png", height = 10, width = 7.5, units = "in")
  
ggsave(variableplot2_recip, filename = "./Outputs/V4 Figures/diffplot_variable_recipientsonly_omega20_2026_06_25.png", height = 10, width = 7.5, units = "in")

#pdf(file = "./Outputs/V3 Figures/diffplot_variable_recipientsonly_updated_2025_11_24.pdf", height = 10, width = 7.5)
#variableplot2_recip
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_variable_mutationtest3_recipientsonly_updated_2026_03_29.pdf", height = 10, width = 7.5)
#variableplot2_recip
#dev.off()

#pdf(file = "./Outputs/V4 Figures/diffplot_variable_recipientsonly_2026_06_07.pdf", height = 10, width = 7.5)
#variableplot2_recip
#dev.off()

pdf(file = "./Outputs/V4 Figures/diffplot_variable_recipientsonly_omega20_2026_06_25.pdf", height = 10, width = 7.5)
variableplot2_recip
dev.off()

```

```{r prerescueextantplots}


pre_extant_plot <- ggplot(data = poplistrescueprerecipsumbyparameter, aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Extant)) + geom_tile() + facet_grid(~EnvType) + scale_fill_viridis(option = "A") + scale_x_continuous(name = "Proportion Migrants", breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = smalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1))

pre_popsize_plot <- ggplot(data = poplistrescueprerecipsumbyparameter, aes(x = log10(Mig+0.000001), y = -(1/Sel), fill = Pop.Size)) + geom_tile() + facet_grid(~EnvType) + scale_fill_viridis(option = "A")+ scale_x_continuous(name = "Proportion Migrants", breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(name = NULL, breaks = -1:-12, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10", "", "1/20"), limits = c(-13,0)) + theme_classic() + theme(axis.text.y = element_text(size = smalltxtsize), axis.text.x  = element_text(size = smalltxtsize, angle = 45, vjust = 1, hjust = 1))

#pdf(file = "./Outputs/V3 Figures/recipients_prerescue_extantupdated.pdf", height = 10, width = 7.5)
#pre_extant_plot
#dev.off()

#pdf(file = "./Outputs/V4 Figures/recipients_prerescue_extantupdated_2026_03_29_mutation3.pdf", height = 10, width = 7.5)
#pre_extant_plot
#dev.off()

#pdf(file = "./Outputs/V4 Figures/recipients_prerescue_extant_2026_06_07.pdf", height = 10, width = 7.5)
#pre_extant_plot
#dev.off()


pdf(file = "./Outputs/V4 Figures/recipients_prerescue_extant_omega20_2026_06_25.pdf", height = 10, width = 7.5)
pre_extant_plot
dev.off()


#pdf(file = "./Outputs/V3 Figures/recipients_prerescue_popsizeupdated.pdf", height = 10, width = 7.5)
#pre_popsize_plot
#dev.off()

#pdf(file = "./Outputs/V4 Figures/recipients_prerescue_popsizeupdated_2026_03_29_mutation3.pdf", height = 10, width = 7.5)
#pre_popsize_plot
#dev.off()

#pdf(file = "./Outputs/V4 Figures/recipients_prerescue_popsize_2026_06_07.pdf", height = 10, width = 7.5)
#pre_popsize_plot
#dev.off()

pdf(file = "./Outputs/V4 Figures/recipients_prerescue_popsize_omega20_2026_06_25.pdf", height = 10, width = 7.5)
pre_popsize_plot
dev.off()

beep()
```
