---
title: "Plots and Analysis"
author: "Ben Wasserman"
date: "`r Sys.Date()`"
output: html_document
---

This script currently processes raw output data from the simulation runs and makes plots (of the no-rescue scenarios).
The processing is quite time-consuming

I'd like to move towards 3-4 files
1. Process no-rescue scenario data
2. Process rescue-scenario data
3 (&4?) Plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(viridis)
library(ggpubr)
library(colorspace)
library(grid)
library(gdata)
library(str2str)
library(parallel)
library(beepr)

```

```{r definefunctions}
datasubset <- function(x){
  filter(x[[1]], Time == 600)
}

```

```{r loaddata}

#Note the parallel processing here is going to be rewritten to be used on a windows machine, but the model itself was run on mac

nameslist <- c("A_2024_03_22", "B_2024_03_23", "C_2024_03_23", "D_2024_03_23", "E_2024_03_24", "F_2024_03_24", "G_2024_03_24", "H_2024_03_24", "J_2025_04_01", "K_2025_04_01", "L_2025_04_02", "M_2025_04_03", "N_2025_04_04", "O_2025_04_07", "P_2025_04_08", "Q_2025_04_09",  "R_2025_04_10", "S_2025_04_10", "T_2025_04_11", "U_2025_04_11", "V_2025_04_15", "W_2025_04_16", "X_2025_04_17", "Y_2025_04_21", "Z_2025_04_22")

#So There was an I dataset, but it was missing data for a single iteration out of the 120. Out of an abundance of caution I'm replacing the whole thing with the Z dataset 

Paramdfcombined <- vector(mode = "list", length = length(nameslist))
results_mclapplycombined <- vector(mode = "list", length(nameslist))
for (i in 1:length(nameslist)) {
  load(file = paste0("Outputs/Parallel/", nameslist[i], "_Outputs.Rdata"))
  Paramdfcombined[[i]] <- Paramdf
  results_mclapplycombined[[i]] <- results_mclapply
}
Paramdfall <- ld2d(Paramdfcombined)

#A-Z (minus I) is 30 iterations, 120x30 = 3600 rows
nrow(Paramdfall)

#This gets us a 3d array with all of the outputs
results_mclapplyall <- unlist(results_mclapplycombined, recursive = FALSE)
beep(sound = 6)


#This gets us a 3d array with all of the outputs
DRlistlist <- lapply(results_mclapplyall, FUN = "[[", 3)
beep(sound = 6)

#I know that DRlistlist[[1]] is blank because the population went extinct
#I thought that the model would always fill that in but apparently not
#DRlistlist[[1351]]<-DRlistlist[[1]]

#DRlistlist <- mclapply(results_mclapplyall, FUN = "[[", 3, mc.cores = 15)
DRlistarray <- lm2a(DRlistlist)

beep(sound = 6)

landlist <- mclapply(results_mclapplyall, FUN = "[[", 2, mc.cores = 1)
landarray <- ld2a(landlist)

landarrayending <- landarray
landarrayending[,1,] <- landarray[,1,]+5

beep(sound = 6)

datalist <- mclapply(results_mclapplyall, FUN = datasubset, mc.cores = 1)
dataarray <- ld2a(datalist)

beep(sound = 4)

datamatrix <- matrix(dataarray, )

save.image("loadedFullList.Rdata")

```

```{r noneendpoint}

load("loadedFullList.Rdata")

#Get the values at the endpoint
poplist <- lapply(datalist, FUN = filter, (Variable == "Pop.Size"))
gradlist <- lapply(datalist, FUN = filter, (Variable == "Grad"))
envlist <- lapply(datalist, FUN = filter, (Variable == "Env"))
gradvarlist <- lapply(datalist, FUN = filter, (Variable == "Grad.Var"))
envvarlist <- lapply(datalist, FUN = filter, (Variable == "Env.Var"))

poparray <- ld2a(poplist)


gradarray <- ld2a(gradlist)
envarray <- ld2a(envlist)
gradvararray <- ld2a(gradvarlist)
envvararray <- ld2a(envvarlist)

Gradmatcharray <- gradarray
Gradmatcharray[,5,] <- as.numeric(Gradmatcharray[,5,]) - rbind(landarrayending[,1,],landarrayending[,1,],landarrayending[,1,],landarrayending[,1,],landarrayending[,1,])

Envmatcharray <- envarray
Envmatcharray[,5,] <- as.numeric(Envmatcharray[,5,]) - rbind(landarrayending[,2,],landarrayending[,2,],landarrayending[,2,],landarrayending[,2,],landarrayending[,2,])


Paramdfall$Extant_None <- apply(matrix(as.numeric(poparray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = function(x) {sum(x>0, na.rm = TRUE)})
Paramdfall$PopSize_None <- apply(matrix(as.numeric(poparray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = mean, na.rm = TRUE)
Paramdfall$Maladapt.Grad_None <- apply(matrix(as.numeric(Gradmatcharray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = mean, na.rm = TRUE)
Paramdfall$Maladapt.Env_None <- apply(matrix(as.numeric(Envmatcharray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = mean, na.rm = TRUE)
Paramdfall$GradVar_None <- apply(matrix(as.numeric(gradvararray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = mean, na.rm = TRUE)
Paramdfall$EnvVar_None <- apply(matrix(as.numeric(envvararray[1:50,5,]), nrow = 50, byrow = FALSE), MARGIN = 2, FUN = mean, na.rm = TRUE)

Paramsum <- Paramdfall %>% dplyr::summarize(across(Extant_None:EnvVar_None, .fns = list(mean = ~mean(.x, na.rm = TRUE), sd = ~sd(.x, na.rm = TRUE))), .by = c(EnvType, Mig, Sel, MuMovement, Omega2grad))

Paramsum$Extant_None_mean[which(Paramsum$Extant_None_mean==0)]<-NA
Paramsum$PopSize_None_mean[which(Paramsum$PopSize_None_mean==0)]<-NA

```


```{r nonesplot}

##Basic two-panel plots

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = Extant_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = PopSize_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = Maladapt.Grad_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = Maladapt.Env_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = GradVar_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

ggplot(data = Paramsum, aes(x = -log10(Mig+0.000001), y = -Omega2grad, fill = EnvVar_None_mean)) + geom_tile() + scale_fill_viridis() + facet_grid(~EnvType) + theme_classic()

##Recreate combined plot, we do each panel singly and then combine



  #Set ranges for plots
  gradmaladaptrange <- range(Paramsum$Maladapt.Grad_None_mean, na.rm = TRUE)
  gradmaladaptrangeround <- c(round(gradmaladaptrange[1], digits = 1)-0.1, round(gradmaladaptrange[2], digits = 1)+0.1)
    envmaladaptrange <- range(Paramsum$Maladapt.Env_None_mean, na.rm = TRUE)
  envmaladaptrangeround <- c(round(envmaladaptrange[1], digits = 1)-0.1, round(envmaladaptrange[2], digits = 1)+0.1)

  
  gradvarmax <- round(max(Paramsum$GradVar_None_mean, na.rm = TRUE),1)
  envvarmax <- ceiling(max(Paramsum$EnvVar_None_mean, na.rm = TRUE))
  
  spacer <- rep(16,4)
  
  smalltxtsize <- 8
  lgtxtsize <- 8


#Rescue Effects Plots is probably the right template

#num extant
extantfixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Extant_None_mean)) + scale_fill_viridis(limits = c(0,50), name = "Populations\nExtant") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

extantvariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Extant_None_mean)) + scale_fill_viridis(limits = c(0,50), name = "Populations\nExtant") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

#avg pop size
popsizefixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = PopSize_None_mean)) + scale_fill_viridis(limits = c(0,500), name = "Population\nSize") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

popsizevariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = PopSize_None_mean)) + scale_fill_viridis(limits = c(0,500), name = "Population\nSize") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

#grad maladapt
gradmalfixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Maladapt.Grad_None_mean)) + scale_fill_gradient2(name = "Gradient-\nPhenotype\nMaladaptation", low = 'red', mid = 'white', high = 'blue', midpoint = 0) + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

gradmalvariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Maladapt.Grad_None_mean)) + scale_fill_gradient2(name = "Gradient-\nPhenotype\nMaladaptation", low = 'red', mid = 'white', high = 'blue', midpoint = 0)  + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

#env maladapt
envmalfixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Maladapt.Env_None_mean)) + scale_fill_gradient2(name = "Environment-\nPhenotype\nMaladaptation", low = 'red', mid = 'white', high = 'blue', midpoint = 0)  + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

envmalvariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = Maladapt.Env_None_mean)) + scale_fill_gradient2(name = "Environment-\nPhenotype\nMaladaptation", low = 'red', mid = 'white', high = 'blue', midpoint = 0)  + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

#grad var
gradvarfixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = GradVar_None_mean)) + scale_fill_viridis(limits = c(0,gradvarmax), name = "Gradient\nPhenotypic\nVariance", option = "magma") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

gradvarvariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = GradVar_None_mean)) + scale_fill_viridis(limits = c(0,gradvarmax), name = "Gradient\nPhenotypic\nVariance", option = "magma") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

#env var
envvarfixed <- ggplot(data = filter(Paramsum, EnvType == "Fixed"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = EnvVar_None_mean)) + scale_fill_viridis(limits = c(0,envvarmax), name = "Environment\nPhenotypic\nVariance", option = "magma") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))

envvarvariable <- ggplot(data = filter(Paramsum, EnvType == "Variable"), aes(x = log10(Mig+0.000001), y = -(1/Sel))) + geom_tile(aes(fill = EnvVar_None_mean)) + scale_fill_viridis(limits = c(0,envvarmax), name = "Environment\nPhenotypic\nVariance", option = "magma") + scale_x_continuous(breaks = log10(c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1)), labels = c("0", "1e-05", "1e-04", "1e-03", "1e-02", "1e-01")) + scale_y_continuous(breaks = -1:-10, labels = c("1", "1/2", "1/3", "1/4", "1/5", "1/6", "1/7", "1/8", "1/9", "1/10")) + theme_classic() + theme(plot.margin = unit(spacer, "points"), axis.title = element_blank(), legend.title=element_text(size = lgtxtsize), axis.text = element_text(size = smalltxtsize), legend.text = element_text(size = smalltxtsize))


explot <- ggarrange(extantfixed, extantvariable, nrow = 1, legend = 'right', common.legend = TRUE)
popplot <- ggarrange(popsizefixed, popsizevariable, nrow = 1, legend = 'right', common.legend = TRUE)
gradplot <- ggarrange(gradmalfixed, gradmalvariable, nrow = 1, legend = 'right', common.legend = TRUE)
envplot <- ggarrange(envmalfixed, envmalvariable, nrow = 1, legend = 'right', common.legend = TRUE)
gradvarplot <- ggarrange(gradvarfixed, gradvarvariable, nrow = 1, legend = 'right', common.legend = TRUE)
envvarplot <- ggarrange(envvarfixed, envvarvariable, nrow = 1, legend = 'right', common.legend = TRUE)

nonesplot <- ggarrange(explot, popplot, gradplot, envplot, gradvarplot, envvarplot, ncol = 1)
nonesplot2 <- annotate_figure(nonesplot, left = textGrob("Selection Strength (1/omega^2)", rot = 90, vjust = 1, gp = gpar(cex=1)), bottom = textGrob("Proportion Migrants", vjust= -0.25, gp = gpar(cex=1)), top = textGrob("Fixed Environment                  Variable Environment", gp = gpar(cex = 1)))
pdf(file = "./Outputs/V2 Figures/nonesplot.pdf", height = 10, width = 7.5)
nonesplot2
dev.off()

```

```{r envmaladapt}
Paramsum2 <- Paramsum %>% mutate(EnvLCI = Maladapt.Env_None_mean - qnorm(0.975)* Maladapt.Env_None_sd/sqrt(30), EnvUCI =  Maladapt.Env_None_mean + qnorm(0.975)* Maladapt.Env_None_sd/sqrt(30), Overlap0 = ((EnvLCI<=0)&(EnvUCI>=0)))

write.csv(Paramsum2, "./Outputs/V2 Figures/Paramsum.csv")

```


```{r rescuedata}
#Here I need to look at "Rescue Effects Plots.Rmd" and modify code from the chunk: RescueLength and beyond.

```